import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen flex flex-col">
        <Header />
        <main className=" flex-grow max-w-4xl mx-auto px-4 py-8">
          {children}
        </main>

        {/* <footer className="bg-white shadow">
          <div className="max-w-4xl mx-auto px-4 py-4 text-center text-gray-600">
            &copy; 2023 Meu Blog. Todos os direitos reservados.
          </div>
        </footer> */}
        <Footer />
      </body>
    </html>
  );
}
